server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: cart-service
          uri: http://localhost:8080
          predicates:
            - Path=/cart/**

        - id: order-service
          uri: http://localhost:8080
          predicates:
            - Path=/orders/**
